# Generated by Django 3.1.5 on 2021-03-20 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='psicologo',
            old_name='nCRP',
            new_name='crp',
        ),
        migrations.AlterField(
            model_name='psicologo',
            name='bio',
            field=models.TextField(blank=True),
        ),
    ]
