# Generated by Django 3.1.5 on 2021-03-25 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psicologo',
            name='bio',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='psicologo',
            name='nCRP',
            field=models.CharField(max_length=200),
        ),
    ]
