# Generated by Django 3.1.5 on 2021-03-25 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210325_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psicologo',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('P', 'Prefiro não responder')], default='M', max_length=1),
        ),
    ]
