# Generated by Django 3.1.5 on 2021-03-19 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=90, verbose_name='Nome completo')),
                ('data_nascimento', models.DateField()),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('P', 'Prefiro não responder')], default=True, max_length=1)),
                ('regiao', models.CharField(choices=[('AC', 'Águas Claras'), ('AS', 'Asa Sul'), ('AN', 'Asa Norte'), ('CI', 'Ceilândia'), ('GA', 'Gama'), ('GA', 'Guará'), ('RE', 'Recanto das Emas'), ('RF', 'Riacho Fundo'), ('SA', 'Samambaia'), ('SO', 'Sobradinho'), ('TA', 'Taguatinga'), ('EO', 'Entre outros')], max_length=3)),
                ('situacao', models.CharField(choices=[('C', 'Controlada'), ('M', 'Moderada'), ('G', 'Grave')], default=True, max_length=2)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
